### ISSUE TITLE
Syntax issue for PRELIM task "Find all sudoers files"

### ISSUE THREAD

**Issue by DianaMariaDDM** [ansible-lockdown/UBUNTU22-CIS#193]
**Describe the Issue**
Small syntax issue in the PRELIM task's name (missing number of a certain task).

**Expected Behavior**
This PRELIM task is needed for rule 5.3.5 as well.

**Actual Behavior**
The task's name includes only the number for task 5.3.4

**Control(s) Affected**

None really, just the title of 
`PRELIM | 5.3.4 | Find all sudoers files.` is not quite accurate.

**Environment (please complete the following information):**
- branch being used: [e.g. devel]

**Additional Notes**
Anything additional goes here

**Possible Solution**
I shall provide the fix in a PR.

**Comment by uk-bolly** [comment]
hi @DianaMariaDDM 

Thank you for your Issues and PRs, these are a great help. However it appears that they all fail the pipeline. I believe this maybe due to your fork not running not in sync with the latest commit in devel.
If you could see if you can sync your fork and then re push your PRs i believe this will fix the issue and the pipelines should pass.
Many thanks again

uk-bolly

**Comment by DianaMariaDDM** [comment]
Hello, thank you as well for your quick reaction!
Yes, I have synced the fork and now those three PRs seem to pass all of the checks.
Thank you for the solution!

**Comment by uk-bolly** [comment]
hi @DianaMariaDDM 

I believe that this issue has been addressed and the fix merged?
I will close this issue, please feel free to reopen or raise a new one if this particular problem still exists.

Many thanks

uk-bolly
