### ISSUE TITLE
1.1.1.1: `cramfs` module has to be explicitly deny-listed for ending up with a CIS-compliant state

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/UBUNTU22-CIS#76]
**Describe the Issue**
###### 0. Initial CIS Assessment, before executing Ansible role: 
```
** PASS **
- Module "cramfs" doesn't exist on the system
```
###### 2a. Afterwards CIS assessment: Rule reported as **failed**.

**Expected Behavior**
##### 2b. Afterwards CIS assessment: Rule reported as **passed**:
```- Audit Result:
  ** PASS **

 - module: "cramfs" is not loadable: "install /bin/true "
 - module: "cramfs" is not loaded
 - module: "cramfs" is deny listed in: "/etc/modprobe.d/cramfs.conf"
```

**Actual Behavior**
###### 2a. Afterwards CIS assessment: Rule reported as **failed**.
```
- Audit Result:
** FAIL **
- Reason(s) for audit failure:
- module: "cramfs" is not deny listed
- Correctly set:
- module: "cramfs" is not loadable: "install /bin/true "
- module: "cramfs" is not loaded
```
**Control(s) Affected**
Rule 1.1.1.1 

**Environment (please complete the following information):**

- branch being used: [e.g. devel]

**Additional Notes**
1.  Red-Hat's approach on preventing kernel modules to be automatically loaded: [Step2 & Step3](https://access.redhat.com/solutions/41278)
2. STIG for RH8, [`cramfs` configuration](https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-12-03/finding/V-230498)
3. OpenSCAP's way of doing it, even if for other OS-baselines([ e.g. Oracle Linux ](https://static.open-scap.org/ssg-guides/ssg-ol7-guide-ospp.html))
>To configure the system to prevent the cramfs from being used, add the following line to file /etc/modprobe.d/cramfs.conf:
blacklist cramfs

**Possible Solution**
I'll add a PR immediately.

**Comment by uk-bolly** [comment]
hi @ipruteanu-sie 

Thank you for raising the issue regarding the cramfs and blacklist. Can you please confirm the branch you are using?
Basing in on devel branch
The problem we see very often is that scanners all work differently and some are very restricted and brittle. In this case they are looking for the blacklist in cramfs.conf rather than ensuring a blacklists exists.

If you look at the system it should be blacklisted in /etc/modprobe.d/blacklist.conf.

This means that is passes the requirement but the scanners are too restrictive on how people may configure their systems.

This is the reason we developed our own configuration so we can amend and fix these as quickly as issues arise to try and remove these false positives

Please let me know if this working as expected?

many thanks

uk-bolly

**Comment by ipruteanu-sie** [comment]
Hi @uk-bolly , 
Thanks for your explanation, I was using indeed `devel` branch, but a not updated version of it.
Last week's update fixed it indeed, CIS reports it properly:
```
- Audit Result:
** PASS **
- module: "cramfs" is not loadable: "install /bin/true "
- module: "cramfs" is not loaded
- module: "cramfs" is deny listed in: "/etc/modprobe.d/blacklist.conf"
```
